"""add_media_fields_to_project_tower_unit

Revision ID: 36e01455ed82
Revises: 0002_field_configs
Create Date: 2026-03-12 18:04:13.384308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36e01455ed82'
down_revision: Union[str, None] = '0002_field_configs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cms_sections_page_key', table_name='cms_sections')
    op.drop_table('cms_sections')
    op.drop_table('cms_pages')
    op.drop_table('site_settings')
    op.alter_column('admin_users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'admin'::character varying"))
    op.alter_column('admin_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('admin_users_username_key', 'admin_users', type_='unique')
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.alter_column('custom_field_values', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('custom_field_values', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_cfv_entity_id', table_name='custom_field_values')
    op.drop_index('ix_cfv_field_config_id', table_name='custom_field_values')
    op.create_index(op.f('ix_custom_field_values_entity_id'), 'custom_field_values', ['entity_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_field_config_id'), 'custom_field_values', ['field_config_id'], unique=False)
    op.alter_column('customers', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('field_configs', 'entity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('field_configs', 'field_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'text'::text"))
    op.alter_column('field_configs', 'show_on_customer',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('field_configs', 'show_on_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('field_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('field_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_logs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_logs', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_logs', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('session_logs', 'page_views',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('session_logs', 'is_customer',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('session_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_session_logs_created', table_name='session_logs')
    op.drop_index('idx_session_logs_customer', table_name='session_logs')
    op.drop_index('idx_session_logs_session', table_name='session_logs')
    op.create_index(op.f('ix_session_logs_customer_id'), 'session_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_session_logs_session_id'), 'session_logs', ['session_id'], unique=False)
    op.add_column('towers', sa.Column('video_url', sa.Text(), nullable=True))
    op.add_column('towers', sa.Column('walkthrough_url', sa.Text(), nullable=True))
    op.add_column('towers', sa.Column('floor_plans', sa.JSON(), nullable=False))
    op.add_column('units', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('units', sa.Column('walkthrough_url', sa.String(length=500), nullable=True))
    op.add_column('units', sa.Column('floor_plans', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'floor_plans')
    op.drop_column('units', 'walkthrough_url')
    op.drop_column('units', 'video_url')
    op.drop_column('towers', 'floor_plans')
    op.drop_column('towers', 'walkthrough_url')
    op.drop_column('towers', 'video_url')
    op.drop_index(op.f('ix_session_logs_session_id'), table_name='session_logs')
    op.drop_index(op.f('ix_session_logs_customer_id'), table_name='session_logs')
    op.create_index('idx_session_logs_session', 'session_logs', ['session_id'], unique=False)
    op.create_index('idx_session_logs_customer', 'session_logs', ['customer_id'], unique=False)
    op.create_index('idx_session_logs_created', 'session_logs', ['created_at'], unique=False)
    op.alter_column('session_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_logs', 'is_customer',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('session_logs', 'page_views',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('session_logs', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('session_logs', 'last_seen_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('session_logs', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('field_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('field_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('field_configs', 'show_on_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('field_configs', 'show_on_customer',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('field_configs', 'field_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'text'::text"))
    op.alter_column('field_configs', 'entity',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('customers', 'last_login',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_custom_field_values_field_config_id'), table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_field_values_entity_id'), table_name='custom_field_values')
    op.create_index('ix_cfv_field_config_id', 'custom_field_values', ['field_config_id'], unique=False)
    op.create_index('ix_cfv_entity_id', 'custom_field_values', ['entity_id'], unique=False)
    op.alter_column('custom_field_values', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('custom_field_values', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.create_unique_constraint('admin_users_username_key', 'admin_users', ['username'])
    op.alter_column('admin_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('admin_users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'admin'::character varying"))
    op.create_table('site_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('setting_key', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('setting_label', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('setting_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('setting_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('group_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='site_settings_pkey'),
    sa.UniqueConstraint('setting_key', name='site_settings_setting_key_key')
    )
    op.create_table('cms_pages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('page_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('page_label', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('seo_title', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('seo_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seo_keywords', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('og_title', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('og_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('og_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('canonical_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cms_pages_pkey'),
    sa.UniqueConstraint('page_key', name='cms_pages_page_key_key')
    )
    op.create_table('cms_sections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('section_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section_label', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('page_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('subtitle', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cta_text', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cta_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cms_sections_pkey'),
    sa.UniqueConstraint('section_key', name='cms_sections_section_key_key')
    )
    op.create_index('ix_cms_sections_page_key', 'cms_sections', ['page_key'], unique=False)
    # ### end Alembic commands ###
