"""initial: all models

Revision ID: 5b9fef923258
Revises: 
Create Date: 2026-03-06 16:14:06.554790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b9fef923258'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('interest', sa.String(length=100), nullable=True),
    sa.Column('budget_min', sa.String(length=50), nullable=True),
    sa.Column('budget_max', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sf_lead_id', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_visits',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visit_time', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('sf_event_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bookings', sa.Column('coupon_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('razorpay_signature', sa.String(length=255), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('bookings', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bookings', 'unit_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bookings', 'discount_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('bookings', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'unpaid'::character varying"))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_bookings_status', table_name='bookings')
    op.create_foreign_key(None, 'bookings', 'coupons', ['coupon_id'], ['id'])
    op.add_column('cart_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('cart_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('cart_items', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('cart_items', 'unit_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('cart_items_customer_id_unit_id_key', 'cart_items', type_='unique')
    op.drop_column('cart_items', 'added_at')
    op.add_column('coupons', sa.Column('applicable_to', sa.JSON(), nullable=False))
    op.add_column('coupons', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('coupons', 'min_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('coupons', 'used_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('coupons', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('coupons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('customers', sa.Column('otp', sa.String(length=10), nullable=True))
    op.add_column('customers', sa.Column('otp_expiry', sa.String(length=50), nullable=True))
    op.alter_column('customers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('customers', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('projects', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('brochure_url', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.alter_column('projects', 'amenities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('projects', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('search_logs', sa.Column('ip_address', sa.String(length=50), nullable=True))
    op.add_column('search_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('search_logs', 'filters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('search_logs', 'results_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('search_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('towers', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('towers', sa.Column('total_units', sa.Integer(), nullable=False))
    op.add_column('towers', sa.Column('images', sa.JSON(), nullable=False))
    op.alter_column('towers', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('towers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('towers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('towers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('units', sa.Column('balconies', sa.Integer(), nullable=False))
    op.add_column('units', sa.Column('plot_area', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('units', sa.Column('floor_plan_img', sa.String(length=500), nullable=True))
    op.add_column('units', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.alter_column('units', 'tower_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('units', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'available'::character varying"))
    op.alter_column('units', 'amenities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('units', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('units', 'is_trending',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('units', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('units', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('units', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_units_embedding', table_name='units', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_units_floor', table_name='units')
    op.drop_index('idx_units_price', table_name='units')
    op.drop_index('idx_units_status', table_name='units')
    op.drop_index('idx_units_tower', table_name='units')
    op.drop_index('idx_units_trending', table_name='units', postgresql_where='(is_trending = true)')
    op.drop_index('idx_units_trgm', table_name='units', postgresql_using='gin')
    op.drop_index('idx_units_type', table_name='units')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_units_type', 'units', ['unit_type'], unique=False)
    op.create_index('idx_units_trgm', 'units', ['unit_type'], unique=False, postgresql_using='gin')
    op.create_index('idx_units_trending', 'units', ['is_trending'], unique=False, postgresql_where='(is_trending = true)')
    op.create_index('idx_units_tower', 'units', ['tower_id'], unique=False)
    op.create_index('idx_units_status', 'units', ['status'], unique=False)
    op.create_index('idx_units_price', 'units', ['base_price'], unique=False)
    op.create_index('idx_units_floor', 'units', ['floor_number'], unique=False)
    op.create_index('idx_units_embedding', 'units', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('units', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('units', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('units', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('units', 'is_trending',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('units', 'images',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('units', 'amenities',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('units', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'available'::character varying"))
    op.alter_column('units', 'tower_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('units', 'is_featured')
    op.drop_column('units', 'floor_plan_img')
    op.drop_column('units', 'plot_area')
    op.drop_column('units', 'balconies')
    op.alter_column('towers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('towers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('towers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('towers', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('towers', 'images')
    op.drop_column('towers', 'total_units')
    op.drop_column('towers', 'description')
    op.alter_column('search_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('search_logs', 'results_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('search_logs', 'filters',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('search_logs', 'updated_at')
    op.drop_column('search_logs', 'ip_address')
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('projects', 'images',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('projects', 'amenities',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('projects', 'is_featured')
    op.drop_column('projects', 'video_url')
    op.drop_column('projects', 'brochure_url')
    op.drop_column('projects', 'address')
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('customers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('customers', 'otp_expiry')
    op.drop_column('customers', 'otp')
    op.alter_column('coupons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('coupons', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('coupons', 'used_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('coupons', 'min_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('coupons', 'updated_at')
    op.drop_column('coupons', 'applicable_to')
    op.add_column('cart_items', sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_unique_constraint('cart_items_customer_id_unit_id_key', 'cart_items', ['customer_id', 'unit_id'])
    op.alter_column('cart_items', 'unit_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cart_items', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('cart_items', 'updated_at')
    op.drop_column('cart_items', 'created_at')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_index('idx_bookings_status', 'bookings', ['status'], unique=False)
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'unpaid'::character varying"))
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('bookings', 'discount_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bookings', 'unit_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('bookings', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('bookings', 'cancelled_at')
    op.drop_column('bookings', 'razorpay_signature')
    op.drop_column('bookings', 'coupon_id')
    op.drop_table('site_visits')
    op.drop_table('leads')
    # ### end Alembic commands ###
